name: CMake on popular Linux distros

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [ubuntu, debian, fedora, archlinux]
        compiler: [gcc, clang]
        build_type: [Release]

    container:
      image: ${{ matrix.distro }}
      options: --privileged  # needed by some distros like archlinux in CI

    steps:
    - name: Install dependencies
      run: |
        if [ "${{ matrix.distro }}" = "ubuntu" ] || [ "${{ matrix.distro }}" = "debian" ]; then
          apt-get update && apt-get install -y cmake g++ gcc clang make libncurses-dev git
        elif [ "${{ matrix.distro }}" = "fedora" ]; then
          dnf install -y cmake gcc gcc-c++ clang make ncurses-devel git
        elif [ "${{ matrix.distro }}" = "archlinux" ]; then
          pacman -Sy --noconfirm cmake gcc clang make ncurses git
        fi

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set build directory
      id: vars
      run: echo "build-dir=${GITHUB_WORKSPACE}/build" >> "$GITHUB_ENV"

    - name: Configure CMake
      run: >
        cmake -B ${{ env.build-dir }}
        -DCMAKE_C_COMPILER=${{ matrix.compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ env.build-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ env.build-dir }}
      run: ctest --output-on-failure
